### ISSUE TITLE
Would you like to share the soruce code?

### ISSUE THREAD

**Issue by isjinghao** [EadCat/EEISN_SPL21#1]
I'd like to fellow your work, I'd appreciate if you can upload your  soruce code please.

**Comment by EadCat** [comment]
Thank you for interesting in our work.

This work is a research outcome of an industry-academic cooperation with ETRI. (https://www.etri.re.kr/eng/main/main.etri)

Although I've been involved in this as a researcher, it's hard to share, since not all of this is mine. In fact, I would like to release the dataset and source code for future studies, but we need permission from ETRI.

Maybe you can ask directly to co-author of ETRI.

**Comment by isjinghao** [comment]
Thanks for your reply, and I'll ask the enterprise you mentioned,  and that's better if you can get permission from ETRI, and release the dataset and source code. Thanks!
