### ISSUE TITLE
Why is the the shape of picture look like an eye?

### ISSUE THREAD

**Issue by DanilHu** [EadCat/EEISN_SPL21#2]
I've recently read about this innovative paper and would like to follow your work. And now I'm using Carla Engine to generate database. But could you please tell me why you made the picture look like an eye instead of a rectangle?  
![Question](https://user-images.githubusercontent.com/40864036/125272971-06b67e00-e33f-11eb-8c98-f1a3d71fd6da.PNG)
Did you use camera configs that distort the lens(if so, could you tell me what parameters you've changed? It took me a lot of time to find those parameters and it still don't work) or just take the frame and project it to an eye surface?

**Comment by EadCat** [comment]
We captured rectangular images and project them to cylindrical coordinates.
This is because we thought it is easier than other coordinate systems to create a 360-degree image using images projected on cylindrical coordinates.

You can refer to the following links:
1. https://github.com/geekyspartan/Image-stitching-panorama
2. https://github.com/TejasNaikk/Image-Alignment-and-Panoramas

Thank you for your interest in our work. :)

good luck!

**Comment by DanilHu** [comment]
Thank you very much for your kind reply! That helps me lot. But there are still several questions that confuse me about this paper which I think maybe not appropriate to ask in this place. Would you mind if I send an email to you? : )

**Comment by EadCat** [comment]
You can send me an email anytime when you want, but if I'm busy, my reply may be late.

I check the following email address periodically : eadyoung@naver.com
